"""Packs WAV clips into a C++ header for the Atom Echo firmware.

Usage: pack_clips.py <wav dir> <output header> <clip name>...

Leading and trailing silence is trimmed so alerts start promptly, and each
clip keeps a valid WAV header because M5.Speaker.playWav() parses it.
"""

import struct
import sys
import wave
from pathlib import Path

SILENCE = 300  # 16-bit sample magnitude treated as silence
PAD_SAMPLES = 800  # 50 ms at 16 kHz kept either side of the speech
# Peaks are scaled to this fraction of full scale. Full-scale speech clips
# distort through the small amplifiers, and equal peaks keep clips equally loud.
PEAK = 0.7


def trimmed_wav(path: Path) -> bytes:
    with wave.open(str(path), "rb") as source:
        rate = source.getframerate()
        if source.getnchannels() != 1 or source.getsampwidth() != 2:
            raise SystemExit(f"{path.name}: expected 16-bit mono")
        frames = source.readframes(source.getnframes())
    samples = struct.unpack(f"<{len(frames) // 2}h", frames)
    loud = [i for i, s in enumerate(samples) if abs(s) > SILENCE]
    if loud:
        start = max(loud[0] - PAD_SAMPLES, 0)
        end = min(loud[-1] + PAD_SAMPLES, len(samples))
        samples = samples[start:end]
    peak = max((abs(s) for s in samples), default=0)
    if peak:
        gain = PEAK * 32767 / peak
        samples = [max(-32768, min(32767, round(s * gain))) for s in samples]
    data = struct.pack(f"<{len(samples)}h", *samples)
    header = struct.pack(
        "<4sI4s4sIHHIIHH4sI",
        b"RIFF", 36 + len(data), b"WAVE", b"fmt ", 16, 1, 1, rate,
        rate * 2, 2, 16, b"data", len(data))
    return header + data


def main() -> None:
    wav_dir, output, *names = sys.argv[1:]
    lines = [
        "// Generated by tools/make_clips.ps1. Do not edit by hand.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace clips {",
        "",
    ]
    total = 0
    for name in names:
        data = trimmed_wav(Path(wav_dir) / f"{name}.wav")
        total += len(data)
        lines.append(f"constexpr std::uint8_t {name}[{len(data)}] = {{")
        for offset in range(0, len(data), 20):
            chunk = data[offset:offset + 20]
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
        lines.append("};")
        lines.append("")
    lines.append("}  // namespace clips")
    lines.append("")
    Path(output).write_text("\n".join(lines), encoding="ascii")
    print(f"Packed {len(names)} clips, {total / 1024:.0f} KB, into {output}")


if __name__ == "__main__":
    main()
